### ISSUE TITLE
Add topic aoc-2024-in-kotlin

### ISSUE THREAD

**Issue by tigerxy** [Andurian/AdventOfCode2024#1]
When you add the topic and join one of official Kotlin leaderboards, you can win some Kotlin swag. Additionally you can watch the stream every evening about how to solve it in idomatic Kotlin. [Here is described how](https://blog.jetbrains.com/kotlin/2024/11/advent-of-code-2024-in-kotlin/). Have fun and see you! :tada:

**Comment by Andurian** [comment]
Thanks for the info. Tag has been added.
